apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: personal

helmCharts:
  - name: cpng
    repo: https://cloudnative-pg.github.io/charts
    version: 0.27.0
    releaseName: cloudnative-pg
    namespace: cpng
    valuesFile: values.yaml
