apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: personal

resources:
  - personal-ns.yaml # we need to move this out (and other namespace definitions into platform?)
  - postgres-cluster.yaml
  - storage.yaml

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    version: 0.10.3
    releaseName: immich
    namespace: personal
    valuesFile: values.yaml
