apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: personal

resources:
  - personal-ns.yaml # we need to move this out (and other namespace definitions into platform?)

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.27.0
    releaseName: cloudnative-pg
    namespace: cpng
    valuesFile: values.yaml
