apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: personal

resources:
  - personal-ns.yaml # we need to move this out (and other namespace definitions into platform?)
  - postgres-cluster.yaml
  - immich-pvc.yaml
  - immich-tailscale-ingress.yaml

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-helm
    version: 2.1.0
    releaseName: immich
    namespace: personal
    valuesFile: values.yaml
