apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - immich-pvc.yaml
  - immich-tailscale-ingress.yaml

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    version: 0.10.3
    releaseName: immich
    namespace: media
    valuesFile: values.yaml
