immich:
  persistence:
    library:
      existingClaim: immich-library-pvc

machine-learning:
  persistence:
    cache:
      existingClaim: immich-ml-pvc

valkey:
  enabled: true

env:
  REDIS_HOSTNAME: "immich-valkey"
  DB_HOSTNAME: "immich-postgres-rw"
  DB_DATABASE_NAME: "immich"
  DB_USERNAME: "immich"
  DB_PASSWORD: "immich"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"

controllers:
  main:
    containers:
      main:
        image:
          tag: v2.0.0