apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiscrobbler
  namespace: media
  labels:
    app: multiscrobbler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiscrobbler
  template:
    metadata:
      labels:
        app: multiscrobbler
    spec:
      containers:
        - name: multi-scrobbler
          image: foxxmd/multi-scrobbler:latest
          ports:
            - containerPort: 9078
              name: http
          envFrom:
            - secretRef:
                name: multiscrobbler-lastfm-creds
          env:
            - name: LZE_TOKEN
              value: "myVeryCoolToken"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: multiscrobbler-config
