apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multiscrobbler
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: ingress
spec:
  ingressClassName: nginx
  rules:
    - host: multiscrobbler.cluster
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: multiscrobbler
                port:
                  number: 9078