apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: personal

resources:
  - postgres-cluster.yaml

helmCharts:
  - name: vaultwarden
    repo: https://guerzon.github.io/vaultwarden
    version: 0.10.3
    releaseName: vaultwarden
    namespace: personal
    valuesFile: values.yaml
