apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

helmCharts:
  - name: navidrome
    repo: https://djjudas21.github.io/charts
    version: 6.7.6
    releaseName: navidrome
    namespace: media
    valuesFile: values.yaml
