apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

helmCharts:
  - name: navidrome
    repo: https://k8s-at-home.com/charts
    version: 1.17.3
    releaseName: navidrome
    namespace: media
    valuesFile: values.yaml
