apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network

resources:
  - namespace.yaml

helmCharts:
  - name: pihole
    repo: https://mojo2600.github.io/pihole-kubernetes
    version: 2.35.0
    releaseName: pihole
    namespace: network
    valuesFile: values.yaml
