ingress:
  enabled: true
  ingressClassName: nginx

  annotations: {
    kubernetes.io/ingress.class: nginx
  }

  hosts:
    - pihole.cluster

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #     #- virtualHost (default value is pi.hole) will be appended to the hosts
  #      - chart-example.local