apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-tailscale
  namespace: personal
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - homeassistant
  defaultBackend:
    service:
      name: home-assistant
      port:
        number: 8123