apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: personal

helmCharts:
  - name: home-assistant
    repo: http://pajikos.github.io/home-assistant-helm-chart/
    version: 0.3.42
    releaseName: home-assistant
    namespace: personal
    valuesFile: values.yaml