apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-server
  namespace: media
  labels:
    app: sftp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp-server
  template:
    metadata:
      labels:
        app: sftp-server
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: sftp-server
        image: atmoz/sftp:latest
        ports:
        - containerPort: 22
        envFrom:
        - secretRef:
            name: sftp-user-credentials
        volumeMounts:
        - name: shared-media
          mountPath: /home/olaf/media
        - name: navidrome-music
          mountPath: /home/olaf/music
      volumes:
      - name: shared-media
        persistentVolumeClaim:
          claimName: shared-media
      - name: navidrome-music
        persistentVolumeClaim:
          claimName: navidrome-music
