apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

helmCharts:
  - name: jellyfin
    repo: https://jellyfin.github.io/jellyfin-helm
    version: 2.7.0
    releaseName: jellyfin
    namespace: media
    valuesFile: values.yaml
